### ISSUE TITLE
Oracle identifier length is limited to 30 characters 

### ISSUE THREAD

**Issue by soyuka** [lexik/LexikTranslationBundle#171]
Hi,

```
  An exception occurred while executing 'CREATE SEQUENCE LEXIK_TRANS_UNIT_TRANSLATIONS_ID_SEQ START WITH 1 MINVALUE 1 INCREMENT BY 1':
ORA-00972: identifier is too long
```

What would be the best practice to change tables names? 

Ref: https://github.com/lexik/LexikTranslationBundle/blob/master/Resources/config/doctrine/TransUnit.orm.xml#L7

**Comment by cedric-g** [comment]
HI, maybe you can extend the bundle and override the entities.

**Comment by cyframepaul** [comment]
I had the same issue. I finally just overrode the direcotry of the mappings and changed the long names to short ones.  

Added to my config.yml :

```
doctrine
    orm:
        entity_managers:
                mappings:
                    LexikTranslationBundle:
                        mapping: true
                        type: yml
                        dir: "%kernel.root_dir%/Resources/LexikTranslationBundle/doctrine/lexik"
                        prefix: Lexik\Bundle\TranslationBundle\Entity
                        is_bundle: false
                        alias: ~

```

Then made a directories "app/Resources/LexikTranslationBundle/doctrine/lexik" and put this in them:

File.orm.yml :

```
Lexik\Bundle\TranslationBundle\Entity\File:
    type: entity
    table: TRANS_FILE
    repositoryClass: Lexik\Bundle\TranslationBundle\Entity\FileRepository
    uniqueConstraints:
        hash_idx:
            columns:
                - hash
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
    oneToMany:
        translations:
            targetEntity: Lexik\Bundle\TranslationBundle\Entity\Translation
            cascade:
                - persist
            fetch: LAZY
            mappedBy: file
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks:
        prePersist:
            - prePersist
        preUpdate:
            - preUpdate
```

Translation.orm.yml :

```
Lexik\Bundle\TranslationBundle\Entity\Translation:
    type: entity
    table: TRANS_UNIT_TRANSLATIONS
    repositoryClass: Lexik\Bundle\TranslationBundle\Entity\TranslationRepository
    uniqueConstraints:
        trans_unit_locale_idx:
            columns:
                - trans_unit_id
                - locale
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
    manyToOne:
        file:
            targetEntity: Lexik\Bundle\TranslationBundle\Entity\File
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: translations
            joinColumns:
                file_id:
                    referencedColumnName: id
            orphanRemoval: false
        transUnit:
            targetEntity: Lexik\Bundle\TranslationBundle\Entity\TransUnit
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: translations
            joinColumns:
                trans_unit_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist:
            - prePersist
        preUpdate:
            - preUpdate

```

TransUnit.orm.yml :

```
Lexik\Bundle\TranslationBundle\Entity\TransUnit:
    type: entity
    table: TRANS_UNIT
    repositoryClass: Lexik\Bundle\TranslationBundle\Entity\TransUnitRepository
    uniqueConstraints:
        key_domain_idx:
            columns:
                - key_name
                - domain
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
    oneToMany:
        translations:
            targetEntity: Lexik\Bundle\TranslationBundle\Entity\Translation
            cascade:
                - all
            fetch: LAZY
            mappedBy: transUnit
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks:
        prePersist:
            - prePersist
        preUpdate:
            - preUpdate

```

On a similar note, don't try renaming "**lexik_translation_file**" table to "**file**". "**file**" is a reserved word in Oracle.
Hope that helps! :smiley:
