### ISSUE TITLE
How does this bundle actually work ??

### ISSUE THREAD

**Issue by manseuk** [lexik/LexikTranslationBundle#213]
Hi, its a great bundle, however im a little confused how it works. I have the following config.yml

```
lexik_translation:
    fallback_locale: en
    managed_locales: [en, fr, de, da, es]
    use_yml_tree: true
    storage:
      type: orm                  # orm | mongodb | propel
      object_manager: default
    base_layout: 'WLGUIBundle::layouts/default.html.twig'
    auto_cache_clean: true
    auto_cache_clean_interval: 3600
```

and i have updated some DE translations using the admin tool - i can see the changes in the database and on the admin front end - so far so good .... they have been changed over 24 hours and still the old translation is visible in the front end of my app.

What i want to be able to do is let people change the translations using the admin tool and for these changes to override the original translations in the yml files. 

Is that possible ?
