### ISSUE TITLE
How to load translations from DB after they are imported?

### ISSUE THREAD

**Issue by reypm** [lexik/LexikTranslationBundle#251]
I have been reading carefully the documentation for this bundle and I have setup my project as follow:

```
# LexikTranslationBundle Configuration
lexik_translation:
    fallback_locale: [en]     
    managed_locales: [en, es]
    storage:
        type: mongodb             
        object_manager: default
```

If I remove the `.xliff` files from the project and try to load translations from DB it doesn't work. Did I miss something here? How do I load the translations directly from DB?

**Comment by cedric-g** [comment]
Hi, if you want to load the translations only from the DB just use:
```
lexik_translation:
    resources_registration:
        type:                 database
        managed_locales_only: true
```

**Comment by reypm** [comment]
@cedric-g that's not working for me. This is how my config looks like:

```
# LexikTranslationBundle Configuration
lexik_translation:
    fallback_locale: [en]
    managed_locales: [en, es]
    storage:
        type: mongodb             
        object_manager: default
    resources_registration:
        type:                 database
        managed_locales_only: true
```
