### ISSUE TITLE
Symfony 3.3.6 

### ISSUE THREAD

**Issue by ArmandArthur** [lexik/LexikTranslationBundle#270]
Hello, i have symfony 3.3.6 and i had use this patch: 
https://github.com/lexik/LexikTranslationBundle/pull/265/commits/b59f6d9da664ec95365d1a16c929244c678b645c

and i have add to the mapping : 
```
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    LexikTranslationBundle: ~
```

And now i have this error. There is a patch to update this error please?

`Type error: Argument 1 passed to Lexik\Bundle\TranslationBundle\Storage\AbstractDoctrineStorage::__construct() must be an instance of Symfony\Bridge\Doctrine\ManagerRegistry, none given, called in C:\wamp64\www\master\var\cache\dev\appDevDebugProjectContainer.php on line 2629`
