### ISSUE TITLE
Wrong special char replacement when saving a translation

### ISSUE THREAD

**Issue by kugaudo** [lexik/LexikTranslationBundle#286]
Hello,

The actual problem I have is that _encodeURIComponent_ breaks all my chars excepting english letters.
E.g. "**_Invalidate cache_**" turns to "**_Invalidate%20cache_**" after pressing Save button.

I had to change this block to fix it:
```js
// web/bundles/lexiktranslation/js/translation.js:82

for (var name in translation) {
    // parameters[name] = encodeURIComponent(translation[name]);
    parameters[name] = translation[name];
}

```

My config is:
```yml
# Lexik Translations
lexik_translation:
    fallback_locale: [en]         # (required) default locale(s) to use
    managed_locales: [en, lv, ru] # (required) locales that the bundle has to manage
    grid_input_type: textarea     # text|textarea
```

PR with _encodeURIComponent_ was added: #72 

What I'm doing wrong?
