### ISSUE TITLE
create_missing not shown

### ISSUE THREAD

**Issue by grekpg** [lexik/LexikTranslationBundle#349]
i setup config : 

```
lexik_translation:
  fallback_locale: [en]         # (required) default locale(s) to use
  managed_locales: [en, pt, pl] # (required) locales that the bundle has to manage

  resources_registration:
    type:                 all  # all | files | database
    managed_locales_only: false

  auto_cache_clean: true

  exporter:
    use_yml_tree: true

  dev_tools:
    enable: true
    create_missing: true
    file_format: yml
```

Go to site when have missing translations and is auto created in table lexik_trans_unit

Go to translations panel and do not see it in list. 

I check bundle read translations from lexik_trans_unit_translations 

How show new auto created translations ?
